### ISSUE TITLE
tiger.svg not rendering correctly

### ISSUE THREAD

**Issue by JaimeIvanCervantes** [igagis/svgren#16] opened 2017-07-05 22:56 UTC
Hello, I was able to render `camera.svg` and other 3 simple svgs correctly using the example on `tests/render/main.cpp` but `tiger.svg` is failing to render properly:

Here's my result when rendering the file `camera.svg`:
![camera](https://user-images.githubusercontent.com/5825034/27888252-eead5ad4-6199-11e7-8899-68a62f973fbb.png)

And here's my result when rendering the file `tiger.svg`:
![tiger](https://user-images.githubusercontent.com/5825034/27888275-10d1aaa2-619a-11e7-80aa-01efa8b477ee.png)

I use the exact same code for both, the only thing that I changed was the name of the file. I wonder if this is just happening to me, or if you also are seeing this issue too?

**Comment by saeitsystems** [comment] 2017-07-06 06:15
I have no problems with svgren. And I render a lot of different complex and simple images with svgren.
When I try to load tiger.svg with AffinityDesigner I get this Message:
![grafik](https://user-images.githubusercontent.com/25054917/27897792-b2f2f542-6222-11e7-89af-da971b66ec88.png)

And this is what Firefox tells me:
![grafik](https://user-images.githubusercontent.com/25054917/27897811-d3fd2712-6222-11e7-86a9-6ca622519923.png)

Opera:
![grafik](https://user-images.githubusercontent.com/25054917/27897882-30826bf0-6223-11e7-9764-f6ed737f720b.png)

The problems seems to be the testfile tiger.svg and not svgren

**Comment by saeitsystems** [comment] 2017-07-06 06:56
In my application svgren renders the tiger.svg without problems:
![grafik](https://user-images.githubusercontent.com/25054917/27899056-f7925b06-6228-11e7-8d04-5315e4ddf449.png)

**Comment by igagis** [comment] 2017-07-06 06:59
I also don't see problems with tiger.svg, at least I tried recently under Windows and under Linux.
@JaimeIvanCervantes on which OS are you trying?

**Comment by saeitsystems** [comment] 2017-07-06 12:43
I got a different tiger.svg from wikipedia which causes a assertion in svgren:
![grafik](https://user-images.githubusercontent.com/25054917/27911457-6787a5b2-6259-11e7-90f0-ffddead0d104.png)

See attached tiger.svg image
[tiger.zip](https://github.com/igagis/svgren/files/1127847/tiger.zip)

**Comment by igagis** [comment] 2017-07-06 12:45
Hm, interesting, let me try...

**Comment by igagis** [comment] 2017-07-06 12:49
Ok, it uses Cubuc_Smooth_Rel elements in some path which is not implemented in svgren. I need to implement it.

**Comment by saeitsystems** [comment] 2017-07-06 12:57
It is not urgent to me but since it is a standard file on wikipmedia it would be better not to have an assertion ...
https://commons.wikimedia.org/wiki/File:Ghostscript_Tiger.svg

**Comment by igagis** [comment] 2017-07-06 13:01
**svgren** is not a complete support of the SVG standard yet, as the standard is quite big, so I implement features on demand. So thank you for finding missing stuff and providing sample SVGs for those, I add all such SVGs to the test data set.
Assertions are only active in Debug configuration, in Release there are no assertions done, but I checked that tiger.svg in Relese mode, it looks quite distorted :)

**Comment by saeitsystems** [comment] 2017-07-06 13:06
In release mode I got this resulz:
![grafik](https://user-images.githubusercontent.com/25054917/27912294-a790a3fe-625c-11e7-87e0-65682b2e070f.png)

**Comment by igagis** [comment] 2017-07-06 13:07
Yep, it's quite distorted because of those missing path steps. I'm trying to fix it now.

**Comment by saeitsystems** [comment] 2017-07-06 13:52
Interesting is taht the new tiger.svg from mediawiki looks identical but is less than half the size of your test tiger.svg

**Comment by igagis** [comment] 2017-07-06 14:09
@saeitsystems obviously, it is because in my tiger.svg version smooth curve steps are converted to non-smooth ones, which are basically identical, only that smooth ones are shorter in writing.
You can see more about smooth/non-smooth cubic curve path steps here https://www.w3.org/TR/SVG/paths.html#PathDataCubicBezierCommands

**Comment by saeitsystems** [comment] 2017-07-06 14:20
@igagis that looks quite complicated .... I think your library is already doing a very good job!
Are there any favorite SVG editors you would recomend? I use AffinityDesigner on Windows or Mac. I tried Inkscape - I didn't like it because the GUI is complicated and not standard windows and there is no UHD support.

**Comment by igagis** [comment] 2017-07-06 15:09
Well, I'm not drawing much SVGs on my own, but when I need to check something or edit some SVG I use Inkscape. Because I mainly use Linux envirnoment, it is easy to install it there and it is quite sufficient for small SVG tweaks. I did not search for better editors, so, no idea what else is available.

**Comment by JaimeIvanCervantes** [comment] 2017-07-06 16:27
I am using macOS Sierra with `clang-802.0.42` and `cairo 1.14.10` (using Homebrew), and I'm saving the results to png with the changes on my PR: https://github.com/igagis/svgren/pull/17

`camera.svg` and other svgs were rendered correctly, it's only `tiger.svg` that doesn't work. Hmm maybe it's something on my side, I'll keep investigating.

**Comment by igagis** [comment] 2017-07-06 18:20
Ok, I think I have also seen some strange results on MacOS, but not that big as your tiger.svg. I will try to reproduce on MacOS.

**Comment by igagis** [comment] 2017-07-06 19:12
I reproduced the problem with tiger.svg on MacOS, same as @JaimeIvanCervantes observes, investigating...

**Comment by igagis** [comment] 2017-07-06 20:14
For some reason, on MacOS the std lib works differently than on other systems.
The problem which causes the tiger.svg bug is that on MacOS the following assertion fails:
````
std::istringstream s("0c");
float d;
s >> d;
assert(!s.fail())
````
any idea how to workaround this?

**Comment by JaimeIvanCervantes** [comment] 2017-07-06 20:46
I am reproducing the failed assertion:

```
#include <iostream>
#include <sstream>
#include <assert.h>

using namespace std;

int main() {
        std::istringstream s("0c");
        float d;
        s >> d;

        cout<<"d="<<d<<endl;

        if (s.fail()) {
                cout<<"Error"<<endl;
        }

        assert(!s.fail());

        return 0;
}
```
And here's the output:

```
d=0
Error
Assertion failed: (!s.fail()), function main, file istreamstringError.cpp, line 18.
Abort trap: 6
```

Thinking about best way to get around it.

**Comment by JaimeIvanCervantes** [comment] 2017-07-06 20:49
I think the `c` next to the `0` is causing the failure. When I use `std::istringstream s("0")` I don't get any errors.

**Comment by igagis** [comment] 2017-07-06 20:54
Sure, but the problem is that exactly this "0c" is a valid part of SVG document which is to be parsed as number 0 and 'c' should be ignored. I'm now implementing some workaround for this.

**Comment by igagis** [comment] 2017-07-06 21:41
@JaimeIvanCervantes 
Ok, the problem was actually in **svgdom**. I made a workaround.
The **svgdom** version **0.2.36** is coming soon, here is the travis build:
https://travis-ci.org/igagis/svgdom/builds
when it is done, you can upgrade **svgdom** via Homebrew.

**Comment by JaimeIvanCervantes** [comment] 2017-07-06 21:50
Excellent thanks for the quick fix! I actually have my own cmake file with svgdom and svgren dependencies, so I just pulled your changes and it works like a charm, `tiger.svg` is rendering correctly now ;)

**Comment by igagis** [comment] 2017-07-07 07:28
There is still other issue with Wikipedia tiger.svg, so reopening this bug for now, though the fix will come soon.

**Comment by igagis** [comment] 2017-07-11 07:47
@saeitsystems
Ok, new packages released to nuget:
**svgdom** version **0.2.40**
**svgren** version **0.4.20**
please try and close the bug.

**Comment by saeitsystems** [comment] 2017-07-11 08:22
The Tiger from wikimedia renders fine now
![grafik](https://user-images.githubusercontent.com/25054917/28058936-ab7fac7a-6622-11e7-942c-79ce1cb7aed0.png)

It seems, I can't close the bug because I didn't open ist

**Comment by igagis** [comment] 2017-07-11 08:29
Good, and Jaime also reported that he had no problems on MacOS now. So, closing the bug. Thank you!

**Closed by igagis** 2017-07-11 08:29 UTC
